// Explicitly configured loopback services only. Credentials stay in memory.
export function localURL(value){const u=new URL(value);if(!['http:','https:'].includes(u.protocol)||!['localhost','127.0.0.1','[::1]'].includes(u.hostname)||u.username||u.password)throw Error('Use a localhost, 127.0.0.1, or [::1] HTTP(S) endpoint.');return u.href;}
export function fillText(value,text){if(typeof value==='string')return value.replaceAll('{{text}}',()=>text);if(Array.isArray(value))return value.map(v=>fillText(v,text));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,fillText(v,text)]));return value;}
async function rpcResult(response,id,signal){
 if(!response.ok)throw Error('Local service returned HTTP '+response.status);
 if(response.status===202)return null;
 if(!response.headers.get('content-type')?.includes('text/event-stream'))return response.json();
 const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';
 try{while(true){const {done,value}=await reader.read();if(done)break;buffer=(buffer+decoder.decode(value,{stream:true})).replace(/\r\n/g,'\n');let end;while((end=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,end);buffer=buffer.slice(end+2);const data=block.split('\n').filter(l=>l.startsWith('data:')).map(l=>l.slice(5).trimStart()).join('\n');if(data){const result=JSON.parse(data);if(result.id===id)return result;}}if(signal.aborted)throw Error('Cancelled');}throw Error('MCP stream ended without a response.');}finally{await reader.cancel();}
}
export class LocalReader {
 constructor(){this.config={mode:'browser'};this.token='';this.id=0;this.session=null;this.protocol='2025-11-25';}
 configure(config,token=''){if(JSON.stringify(config)!==JSON.stringify(this.config)){this.session=null;this.initialized=false;}this.config=config;this.token=token;}
 async rpc(method,params,signal,notification=false){const id=notification?undefined:++this.id;const response=await fetch(localURL(this.config.url),{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream',...(this.token?{Authorization:'Bearer '+this.token}:{}),...(this.session?{'Mcp-Session-Id':this.session}:{}),...(this.initialized?{'MCP-Protocol-Version':this.protocol}:{})},body:JSON.stringify({jsonrpc:'2.0',...(id?{id}:{}),method,params}),signal});const sid=response.headers.get('Mcp-Session-Id');if(sid)this.session=sid;if(notification){if(!response.ok)throw Error('MCP initialization notification failed.');return;}const result=await rpcResult(response,id,signal);if(result?.error)throw Error(result.error.message||'MCP request failed');return result?.result;}
 async connect(signal){if(this.initialized)return;const result=await this.rpc('initialize',{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:'mindsight',version:'3.3.0'}},signal);if(!['2025-11-25','2025-06-18','2025-03-26'].includes(result?.protocolVersion))throw Error('This connector supports MCP Streamable HTTP versions 2025-03-26 through 2025-11-25.');this.protocol=result.protocolVersion;this.initialized=true;try{await this.rpc('notifications/initialized',{},signal,true);}catch(e){this.initialized=false;throw e;}}
 async list(){const signal=AbortSignal.timeout(15000);await this.connect(signal);let cursor,all=[];do{const r=await this.rpc('tools/list',cursor?{cursor}:{},signal);all.push(...(r.tools||[]));cursor=r.nextCursor;}while(cursor);return all;}
 async audio(text,signal){const c=this.config;localURL(c.url);
 if(c.mode==='api'){const response=await fetch(c.url,{method:'POST',headers:{'Content-Type':'application/json',...(this.token?{Authorization:'Bearer '+this.token}:{})},body:JSON.stringify({model:c.model,voice:c.voice,input:text,response_format:'mp3'}),signal});if(!response.ok)throw Error('Speech API returned HTTP '+response.status);const blob=await response.blob();if(!blob.size||blob.type.includes('json')||blob.type.includes('text'))throw Error('Speech API must return an audio file.');return blob;}
 await this.connect(signal);if(!c.tool)throw Error('Choose a speech tool first.');const template=JSON.parse(c.arguments||'{"text":"{{text}}"}');if(!JSON.stringify(template).includes('{{text}}'))throw Error('Tool arguments must include {{text}}.');const result=await this.rpc('tools/call',{name:c.tool,arguments:fillText(template,text)},signal);if(result?.isError)throw Error('MCP speech tool reported an error.');const audio=result?.content?.find(x=>x.type==='audio'&&x.mimeType?.startsWith('audio/'));if(!audio?.data)throw Error('The MCP tool must return an audio content block (base64 data and audio MIME type).');return new Blob([Uint8Array.from(atob(audio.data),c=>c.charCodeAt(0))],{type:audio.mimeType});
 }
 async speak(text){this.cancel();const controller=this.controller=new AbortController();const timer=setTimeout(()=>controller.abort(),90000);let url;
 try{const blob=await this.audio(text,controller.signal);if(controller.signal.aborted)return;url=URL.createObjectURL(blob);const audio=this.player=new Audio(url);await new Promise((resolve,reject)=>{this.finish=resolve;audio.onended=resolve;audio.onerror=()=>reject(Error('Local speech audio could not play.'));controller.signal.addEventListener('abort',()=>reject(Error('Local speech timed out or was cancelled.')),{once:true});audio.play().catch(reject);});}
 finally{clearTimeout(timer);if(url)URL.revokeObjectURL(url);if(this.controller===controller){this.player?.pause();this.player=null;this.controller=null;this.finish=null;}}
 }
 cancel(){this.controller?.abort();this.player?.pause();this.finish?.();}
}
