import {shapeSVG} from './targets.js?v=3.4.0';
const safeJSON=value=>JSON.stringify(value).replace(/</g,'\\u003c');
const dataURL=blob=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob);});
export function replayPlayer(session,segments,shapeSVG){
 const $=id=>document.getElementById(id),colors={red:'#e14640',blue:'#3076dc',yellow:'#f4cb38',green:'#359b68'};
 const origin=Date.parse(session.createdAt),events=[...(session.events||[])].sort((a,b)=>Date.parse(a.at)-Date.parse(b.at));
 if(!events.some(e=>e.type==='screen')){for(const t of session.trials||[]){if(t.startedAt)events.push({type:'screen',at:t.startedAt,phase:'explore',target:t.target,number:t.number,kind:session.exercise==='compare'?'compare':session.exercise.startsWith('color')&&!session.exercise.toLowerCase().includes('shape')&&!session.exercise.toLowerCase().includes('outline')?'color':['numbers','letters'].includes(session.exercise)?'symbol':session.exercise==='location'?'location':'shape'});}events.sort((a,b)=>Date.parse(a.at)-Date.parse(b.at));$('notice').textContent='Earlier session: target timing is reconstructed from trial start times where available; exact screen transitions may be missing.';}
 let end=origin;for(const e of events)end=Math.max(end,Date.parse(e.at)||origin);for(const s of segments)end=Math.max(end,s.end||s.at);end=Math.max(end,Date.parse(session.completedAt)||origin);
 const duration=Math.max(1,(end-origin)/1000),frames=events.filter(e=>e.type==='screen'),prompts=events.filter(e=>e.type==='prompt'),utterances=events.filter(e=>e.type==='utterance');
 let position=0,playing=false,previous=performance.now(),rate=1,offset=0,externalURL=null,lastFrame=null;
 let audioMeta=segments,players=[];
 function replacePlayers(meta){for(const a of players){a.pause();a.removeAttribute('src');a.load();}audioMeta=meta;players=meta.map(s=>{const a=new Audio(s.url);a.preload='auto';a.onloadedmetadata=()=>sync(true);a.onerror=()=>{$('audioStatus').textContent='Audio cannot play in this browser. Try another audio format.';};return a;});$('audioStatus').textContent=meta.length?`${meta.length} audio segment(s) loaded.`:'No embedded audio. You can attach a recording below.';}
 replacePlayers(segments);
 const fmt=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
 function last(list,at){let lo=0,hi=list.length-1,answer=null;while(lo<=hi){const mid=(lo+hi)>>1;if(Date.parse(list[mid].at)<=at){answer=list[mid];lo=mid+1;}else hi=mid-1;}return answer;}
 function render(){
  const at=origin+position*1000,f=last(frames,at),screen=$('screen');
  if(f!==lastFrame){lastFrame=f;screen.replaceChildren();screen.style.background='#f6f5ef';if(f?.target){const t=f.target;if(f.kind==='color'||f.kind==='compare')screen.style.background=colors[f.kind==='compare'?(f.part===2?t.second:t.first):t.answer]||'#f6f5ef';else {const el=document.createElement('div');if(f.kind==='symbol'){el.className='target-symbol';el.textContent=t.answer.toUpperCase();}else {el.className='target-art';el.innerHTML=shapeSVG(f.kind==='location'?{shape:'circle'}:t);if(f.kind==='location')el.style.left=t.answer==='left'?'25%':'75%';}screen.append(el);}}}
  $('stage').textContent=f?f.phase+(f.number?' · target '+f.number:''):'Session beginning';$('prompt').textContent=last(prompts,at)?.text||'';
  const t=(session.trials||[]).filter(t=>Date.parse(t.at)<=at).at(-1);$('answer').textContent=t?'Recorded response: '+(t.answer||t.status):'';
  $('heard').textContent=last(utterances,at)?'Recognition (unverified): '+last(utterances,at).text:'';
  $('seek').value=position;$('seek').setAttribute('aria-valuetext',fmt(position)+' of '+fmt(duration));$('time').textContent=fmt(position)+' / '+fmt(duration);$('play').textContent=playing?'Pause':'Play';$('play').setAttribute('aria-label',playing?'Pause replay':'Play replay');
 }
 function activeIndex(){const at=origin+position*1000;return audioMeta.findIndex((s,i)=>{const start=s.at+offset*1000,next=(audioMeta[i+1]?.at??Infinity)+offset*1000,a=players[i],len=Number.isFinite(a.duration)?a.duration*1000:s.end?s.end-s.at:Infinity;return at>=start&&at<Math.min(start+len,next);});}
 function sync(force=false){const active=activeIndex();players.forEach((a,i)=>{a.playbackRate=rate;a.volume=Number($('volume').value);a.muted=$('mute').checked;if(i!==active||!playing)a.pause();if(i===active){const wanted=Math.max(0,(origin+position*1000-audioMeta[i].at)/1000-offset);if(force||Math.abs(a.currentTime-wanted)>.35)try{a.currentTime=wanted;}catch{}if(playing&&a.paused&&!a._starting){a._starting=true;a.play().catch(()=>{playing=false;render();$('audioStatus').textContent='Audio playback was blocked. Press Play to try again.';}).finally(()=>a._starting=false);}}});}
 function seek(value){position=Math.max(0,Math.min(duration,value));previous=performance.now();render();sync(true);}
 function toggle(){if(position>=duration)seek(0);playing=!playing;previous=performance.now();render();sync(true);}
 $('play').onclick=toggle;$('rewind').onclick=()=>seek(position-10);$('forward').onclick=()=>seek(position+10);$('restart').onclick=()=>seek(0);$('seek').max=duration;$('seek').oninput=()=>seek(Number($('seek').value));
 $('speed').onchange=()=>{rate=Number($('speed').value);previous=performance.now();sync();};$('volume').oninput=()=>sync();$('mute').onchange=()=>sync();
 $('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('player').requestFullscreen();}catch{$('notice').textContent='Fullscreen is unavailable here. Open the downloaded replay in a browser tab.';}};
 $('audioOffset').oninput=()=>{offset=Number($('audioOffset').value)||0;sync(true);};
 $('attachAudio').onchange=()=>{const file=$('attachAudio').files[0];if(!file)return;if(externalURL)URL.revokeObjectURL(externalURL);externalURL=URL.createObjectURL(file);replacePlayers([{at:origin,url:externalURL}]);sync(true);};
 $('restoreAudio').onclick=()=>{replacePlayers(segments);if(externalURL){URL.revokeObjectURL(externalURL);externalURL=null;}$('attachAudio').value='';offset=0;$('audioOffset').value=0;sync(true);};
 document.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||e.target.matches('input,select,textarea,button'))return;const k=e.key.toLowerCase();if([' ','k','j','l','arrowleft','arrowright','home','end'].includes(k)){e.preventDefault();if(k===' '||k==='k')toggle();else if(k==='home')seek(0);else if(k==='end')seek(duration);else seek(position+(['j','arrowleft'].includes(k)?-10:10));}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){playing=false;sync();render();}});
 $('meta').textContent=session.exercise+' · '+session.mode+' · '+new Date(session.createdAt).toLocaleString();$('notes').textContent=(session.notes||[]).map(n=>n.text).join('\n\n')+(session.reflectionDraft?'\n\nUnsaved draft: '+session.reflectionDraft:'');
 function tick(now){if(playing){const i=activeIndex(),a=players[i];if(a&&!a.paused&&!a.seeking&&a.readyState>=2)position=(audioMeta[i].at-origin)/1000+offset+a.currentTime;else position+=(now-previous)/1000*rate;position=Math.min(duration,position);if(position>=duration)playing=false;render();sync();}previous=now;requestAnimationFrame(tick);}render();requestAnimationFrame(tick);
}
export async function replayDocument(session,segments=[]){
 const audio=await Promise.all(segments.map(async s=>({at:s.startedAt,end:s.endedAt,url:await dataURL(s.blob)})));
 return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MindSight session replay</title><style>
*{box-sizing:border-box}body{margin:0;background:#141a17;color:#eee;font:16px system-ui}main{max-width:1150px;margin:auto;padding:24px}button,input,select{font:inherit}button,select{border:1px solid #67776c;border-radius:6px;background:#28382e;color:#fff;padding:9px 13px;cursor:pointer}button:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid #efd886;outline-offset:3px}#player{background:#090c0a;border:1px solid #536457;border-radius:12px;overflow:hidden}#stageView{position:relative;aspect-ratio:16/9;min-height:240px;max-height:50vh}#screen{position:absolute;inset:0;background:#f6f5ef;color:#171717;overflow:hidden}.target-art{position:absolute;left:50%;top:38%;transform:translate(-50%,-50%);width:22%;height:40%}.target-art svg{width:100%;height:100%}.target-symbol{position:absolute;left:50%;top:38%;transform:translate(-50%,-50%);font:clamp(70px,12vw,170px) Georgia}.overlay{position:absolute;bottom:0;left:0;right:0;padding:18px 22px;background:#111b16ed;color:#fff}.overlay p{margin:5px 0;line-height:1.45;font-size:clamp(12px,1.3vw,16px)}#stage{font-size:12px;text-transform:uppercase;letter-spacing:2px;color:#c2d6c7}#answer{color:#e9d995}.controls{padding:15px;display:flex;flex-wrap:wrap;gap:10px;align-items:center}.controls label{font-size:12px;display:flex;align-items:center;gap:6px}#seek{width:100%;accent-color:#bdcfb4}#volume{width:85px}#time{font-variant-numeric:tabular-nums;font-size:13px}p{line-height:1.6}pre{white-space:pre-wrap}small,#heard{color:#bbc7bf}details{margin:18px 0;border:1px solid #46574c;padding:15px;border-radius:8px}summary{cursor:pointer}details label{display:block;margin:14px 0}input[type=number]{width:90px;padding:8px;background:#28382e;color:#fff;border:1px solid #67776c}#player:fullscreen{width:100vw;height:100vh;border:0;border-radius:0;display:flex;flex-direction:column;justify-content:center}#player:fullscreen #stageView{flex:1;min-height:0;max-height:none;aspect-ratio:auto}#player:fullscreen .target-art{width:25vh;height:25vh}.privacy{font-size:12px;color:#bbc7bf}@media(max-width:600px){main{padding:10px}.controls{gap:8px;padding:10px}.overlay{padding:10px}.target-art{top:30%}.target-symbol{top:30%}}
</style><main><h1>MindSight · session replay</h1><p id="meta"></p><div id="player"><div id="stageView"><div id="screen"></div><div class="overlay"><div id="stage"></div><p id="prompt"></p><p id="answer"></p></div></div><div class="controls"><input id="seek" type="range" min="0" step="0.1" aria-label="Session position"><button id="restart" aria-label="Restart replay">↤ Start</button><button id="rewind" aria-label="Rewind 10 seconds">−10 s</button><button id="play">Play</button><button id="forward" aria-label="Fast forward 10 seconds">+10 s</button><span id="time"></span><label>Speed<select id="speed"><option value="0.5">0.5×</option><option value="0.75">0.75×</option><option value="1" selected>1×</option><option value="1.25">1.25×</option><option value="1.5">1.5×</option><option value="2">2×</option><option value="3">3×</option></select></label><label>Volume<input id="volume" type="range" min="0" max="1" value="1" step="0.05"></label><label><input id="mute" type="checkbox">Mute</label><button id="fullscreen">Fullscreen</button></div></div><p id="notice" role="status">Simulated screen playback, synchronized to saved audio when available. No video file needed.</p><p id="audioStatus" role="status"></p><details><summary>Attach or synchronize a recording</summary><label>Audio file<input id="attachAudio" type="file" accept="audio/*"></label><label>Audio offset in session seconds <input id="audioOffset" type="number" value="0" step="0.1"></label><p>Positive values start the audio later in the session. Negative values skip audio recorded before the session. Embedded recordings use their original timestamps. Attached files stay on your device and are not added to this HTML file.</p><button id="restoreAudio">Restore embedded audio & timing</button></details><details><summary>Recognition text and notes</summary><p id="heard"></p><pre id="notes"></pre></details><p class="privacy">Keyboard: Space / K play or pause, J / Left rewind, L / Right forward, Home / End seek. Tab reaches every control. Audio contains microphone input; guide prompts are shown as text. Recognition is unverified. This file contains personal session data and any embedded audio. It works offline.</p></main><script>(${replayPlayer.toString()})(${safeJSON(session)},${safeJSON(audio)},${shapeSVG.toString()});</script></html>`;
}
