const safeJSON=value=>JSON.stringify(value).replace(/</g,'\\u003c');
const dataURL=blob=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob);});
export async function replayDocument(session,segments=[]){
 const audio=await Promise.all(segments.map(async s=>({at:s.startedAt,end:s.endedAt,url:await dataURL(s.blob)})));
 return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MindSight session replay</title><style>body{margin:0;background:#171e19;color:#eee;font:16px system-ui}main{max-width:950px;margin:auto;padding:24px}button,input{font:inherit}button{padding:10px;margin:5px}#screen{height:45vh;min-height:220px;position:relative;overflow:hidden;border-radius:12px;color:#111;background:#f6f5ef}#symbol{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);font:150px Georgia}#shape{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:130px;height:130px;background:#171717}#shape.circle{border-radius:50%}#shape.triangle{clip-path:polygon(50% 0,100% 100%,0 100%)}#shape.star{clip-path:polygon(50% 0,61% 35%,98% 35%,68% 57%,79% 91%,50% 70%,21% 91%,32% 57%,2% 35%,39% 35%)}#shape.horizontal{height:18px;width:200px}#shape.vertical{width:18px;height:200px}#seek{width:100%}p{line-height:1.6}pre{white-space:pre-wrap}small{color:#bcc7be}</style><main><h1>MindSight · session replay</h1><p id="meta"></p><div id="screen"></div><p id="stage"></p><p id="prompt"></p><p id="answer"></p><p id="heard"></p><button id="play">Play</button><span id="time"></span><input id="seek" type="range" min="0" step="0.1" aria-label="Session position"><p><small>Microphone recording only; guide prompts appear as text. Recognition text is unverified and may contain errors. This file contains the session’s targets, answers, notes and any included audio. No network connection is needed.</small></p><details><summary>Notes and reflection</summary><pre id="notes"></pre></details></main><script>
const session=${safeJSON(session)},segments=${safeJSON(audio)};
const events=session.events||[],frames=events.filter(e=>e.type==='screen'),origin=Date.parse(session.createdAt),end=Math.max(origin,...events.map(e=>Date.parse(e.at)),...segments.map(s=>s.end||s.at));
let duration=Math.max(1,(end-origin)/1000),position=0,playing=false,previous=0;const $=id=>document.getElementById(id),players=segments.map(s=>new Audio(s.url));
$('meta').textContent=session.exercise+' · '+session.mode+' · '+new Date(session.createdAt).toLocaleString();$('notes').textContent=(session.notes||[]).map(n=>n.text).join('\\n\\n')+(session.reflectionDraft?'\\n\\nUnsaved draft: '+session.reflectionDraft:'');$('seek').max=duration;
const colors={red:'#e14640',blue:'#3076dc',yellow:'#f4cb38',green:'#359b68'};
function last(type,at){return events.filter(e=>e.type===type&&Date.parse(e.at)<=at).at(-1);}
function render(){const at=origin+position*1000,f=last('screen',at),s=$('screen');s.replaceChildren();s.style.background='#f6f5ef';if(f?.target){const t=f.target;if(f.kind==='color'||f.kind==='compare')s.style.background=colors[f.kind==='compare'?(f.part===2?t.second:t.first):t.answer]||'#f6f5ef';else {const el=document.createElement('div');el.id=f.kind==='symbol'?'symbol':'shape';if(f.kind==='symbol')el.textContent=t.answer.toUpperCase();else {el.className=f.kind==='location'?'circle':t.answer;if(f.kind==='location')el.style.left=t.answer==='left'?'25%':'75%';}s.append(el);}}$('stage').textContent=f?f.phase+(f.number?' · target '+f.number:''):'Session beginning';$('prompt').textContent=last('prompt',at)?.text||'';const trial=session.trials.filter(t=>Date.parse(t.at)<=at).at(-1);$('answer').textContent=trial?'Last recorded response: '+(trial.answer||trial.status):'';$('heard').textContent=last('utterance',at)?'Recognition (unverified): '+last('utterance',at).text:'';$('seek').value=position;$('time').textContent=Math.floor(position/60)+':'+String(Math.floor(position%60)).padStart(2,'0')+' / '+Math.floor(duration/60)+':'+String(Math.floor(duration%60)).padStart(2,'0');}
function sync(){const at=origin+position*1000;players.forEach((a,i)=>{const offset=(at-segments[i].at)/1000,next=segments[i+1]?.at??Infinity,active=offset>=0&&at<next&&(offset<a.duration||!Number.isFinite(a.duration));if(active){if(Math.abs(a.currentTime-offset)>.6)try{a.currentTime=offset;}catch{}if(playing&&a.paused)a.play().catch(()=>{$('heard').textContent='Audio could not play. Try Play again or use the separate audio file.';});}else a.pause();if(!playing)a.pause();});}
$('play').onclick=()=>{if(position>=duration)position=0;playing=!playing;$('play').textContent=playing?'Pause':'Play';previous=performance.now();sync();};$('seek').oninput=()=>{position=Number($('seek').value);render();sync();};function tick(now){if(playing){position=Math.min(duration,position+(now-previous)/1000);render();sync();if(position>=duration){playing=false;$('play').textContent='Play';sync();}}previous=now;requestAnimationFrame(tick);}render();requestAnimationFrame(tick);
</script></html>`;
}
