import test from 'node:test';
import assert from 'node:assert/strict';
import {Session,exerciseFor,makeTarget,parseIntent,stats} from '../js/core.js';
import {previewHistory,validateSession} from '../js/history.js';
import {shapeSVG} from '../js/targets.js';
test('custom color subset controls generation, recognition, scoring and recovery',()=>{const config={answers:['yellow','green']},s=new Session({exercise:'color4',config});for(let i=0;i<40;i++)assert.ok(config.answers.includes(makeTarget('color4',undefined,config).answer));assert.equal(parseIntent('my answer is red','color4','explore',config).answer,null);s.target();s.propose(s.data.current.target.answer);s.commit();assert.equal(stats(s.data).chance,.5);assert.deepEqual(new Session({},s.data).data.config,config);});
test('colored outline combinations are uniform and contain explicit render metadata',()=>{const config={shapes:['circle','triangle'],colors:['blue','yellow'],style:'outline',ask:'both'},ex=exerciseFor('shapes',config);assert.deepEqual(ex.answers,['blue circle','blue triangle','yellow circle','yellow triangle']);for(let i=0;i<4;i++){const t=makeTarget('shapes',()=>i,config);assert.equal(t.answer,ex.answers[i]);assert.equal(t.style,'outline');assert.equal(t.color+' '+t.shape,t.answer);assert.match(shapeSVG(t),/fill="none"/);}assert.equal(stats(new Session({exercise:'shapes',config}).data).chance,.25);});
test('shape-only and color-only scoring do not count irrelevant variation as answers',()=>{for(const ask of ['shape','color']){const config={shapes:['circle','square'],colors:['red','blue'],style:'solid',ask};assert.equal(exerciseFor('shapes',config).answers.length,2);const t=makeTarget('shapes',()=>0,config);assert.equal(t.answer,ask==='shape'?'circle':'red');}assert.throws(()=>exerciseFor('shapes',{shapes:['circle'],colors:['black'],ask:'shape'}),/at least two/);assert.throws(()=>exerciseFor('color4',{answers:['blue','blue']}));});
function session(){const s=new Session({exercise:'color2'});s.target();s.propose('red');s.commit();s.finish();return s.data;}
test('history accepts single, array, journal and skips existing or repeated IDs',()=>{const s=session();assert.equal(previewHistory(s).additions.length,1);assert.equal(previewHistory([s,s]).duplicates,1);assert.equal(previewHistory({sessions:[s]},[s]).additions.length,0);assert.equal(validateSession(s).reflectionListening,false);});
test('history rejects unsafe or corrupt trials before any records can be merged',()=>{const s=session();s.id='"><img src=x>';assert.throws(()=>previewHistory(s),/ID/);s.id='safe';s.trials[0].number='<b>';assert.throws(()=>previewHistory(s),/trial/);s.trials[0].number=1;s.trials[0].target.answer='purple';assert.throws(()=>previewHistory(s),/target/);});
test('earlier exports are preserved separately instead of reinterpreted as modern scores',()=>{const raw=[{game:'colors',score:4}];const p=previewHistory({legacy:true,rawSessions:raw});assert.equal(p.kind,'legacy');assert.deepEqual(p.rawSessions,raw);assert.equal(previewHistory(raw).kind,'legacy');});
test('new presets retain their configuration after JSON export/import',()=>{for(const exercise of ['coloredShapes','outlines','coloredOutlines']){const s=new Session({exercise});s.target();s.propose(s.data.current.target.answer);s.commit();s.finish();assert.equal(previewHistory(JSON.parse(JSON.stringify(s.data))).additions.length,1);}});
