import test from 'node:test';
import assert from 'node:assert/strict';
import {Session} from '../js/core.js';
import {LESSONS,lessonState,recommendation,comparisonKey,comparableGroups} from '../js/learning.js';
import {journalCard,observationTarget,filterSessions} from '../js/journal.js';
import {cleanPreset,cleanPreferences} from '../js/setups.js';
import {makeBackup,previewBackup,writeStorageBatch} from '../js/backup.js';
function block(options={},hits=true){const s=new Session({exercise:'color2',planned:8,...options});for(let i=0;i<8;i++){s.target();s.propose(hits?s.data.current.target.answer:(s.data.current.target.answer==='red'?'blue':'red'));s.commit();}s.finish();return s.data;}
test('the opening lessons have distinct processes and previous practice counts without claiming new lesson completion',()=>{assert.notDeepEqual(LESSONS.welcome.steps,LESSONS.known.steps);assert.notDeepEqual(LESSONS.known.steps,LESSONS.first.steps);const old=block({lesson:'0-0'});assert.equal(lessonState('welcome',[old]),'Practiced');const fresh=block({lesson:'first'});assert.equal(lessonState('first',[fresh]),'Lesson complete');});
test('recommendations advance after familiarization and include uncertain evidence only across sufficient comparable answers',()=>{assert.equal(recommendation([]).lesson,'welcome');const a=block(),b=block();assert.equal(recommendation([a,b]).signal,'Results informed');assert.match(recommendation([a,b]).reason,/16 of 16/);a.trials.forEach(t=>t.flags.push('leak'));assert.notEqual(recommendation([a,b]).signal,'Results informed');const known=new Session({exercise:'color2',lesson:'known'});known.event('screen',{kind:'color',phase:'familiar',target:{answer:'blue'}});known.finish();known.data.lessonCompleted=true;assert.equal(recommendation([known.data]).lesson,'first');});
test('custom sets are compared by their meaning and never pooled across conditions or answer counts',()=>{const a=block({config:{answers:['blue','red']}}),b=block({config:{answers:['red','blue']}});assert.equal(comparisonKey(a),comparisonKey(b));b.condition='Unmasked, closed eyes';assert.notEqual(comparisonKey(a),comparisonKey(b));assert.equal(comparableGroups([a,b]).length,2);b.condition=a.condition;b.mode='measurement';assert.equal(comparableGroups([a,b]).length,2);});
test('target previews link old observations to trials, retain shape metadata and escape notes',()=>{const r=block();r.notes=[{phase:'explore',trial:1,text:'<img src=x>',at:r.createdAt}];assert.equal(observationTarget(r,r.notes[0]),r.trials[0].target);assert.doesNotMatch(journalCard(r,false),/target-thumbnail/);assert.match(journalCard(r,true),/target-thumbnail/);assert.match(journalCard(r,true),/&lt;img/);r.mode='measurement';r.status='active';assert.equal(observationTarget(r,r.notes[0]),null);assert.doesNotMatch(journalCard(r,true),/target-thumbnail/);assert.match(journalCard(r,true),/sealed until completion/);assert.equal(filterSessions([r],{query:'img'}).length,1);});
test('a full backup round trip retains audio bytes, setups, old archives and omits reader tokens',async()=>{const r=block();r.hasAudio=true;const preset=cleanPreset({id:'evening',name:'Evening',exercise:'shapes',inputMode:'keyboard',condition:'Unmasked, closed eyes',config:{shapes:['star','circle'],colors:['red','blue'],style:'outline',ask:'both'}});const audio=new Blob([new Uint8Array([0,1,255,128])],{type:'audio/ogg;codecs=opus'});const data=await makeBackup({sessions:[r],preferences:{reader:{mode:'api',url:'http://localhost:8000',token:'SECRET'},setup:preset},presets:[preset],archives:[{name:'old',rawSessions:[{score:4}]}],legacy:[{score:2}]},async()=>[{id:'segment-1',startedAt:10,endedAt:40,blob:audio}]);assert.doesNotMatch(JSON.stringify(data),/SECRET/);const restored=previewBackup(JSON.parse(JSON.stringify(data)));assert.equal(restored.additions.length,1);assert.equal(restored.presets[0].inputMode,'keyboard');assert.equal(restored.archives.length,1);assert.equal(restored.legacy.length,1);assert.deepEqual(new Uint8Array(await restored.audio[0].blob.arrayBuffer()),new Uint8Array([0,1,255,128]));assert.equal(previewBackup(data,[r]).duplicates,1);});
test('backup reports unavailable audio and rejects corrupt recordings before import',async()=>{const r=block();r.hasAudio=true;const data=await makeBackup({sessions:[r],preferences:{}},async()=>[]);assert.deepEqual(data.missingAudio,[r.id]);data.audio=[{session:r.id,id:'s',startedAt:2,endedAt:1,mimeType:'audio/ogg',data:'YQ=='}];assert.throws(()=>previewBackup(data),/timing/);data.audio[0].endedAt=3;data.audio[0].data='not audio';assert.throws(()=>previewBackup(data),/encoding/);});
test('failed multi-key restore rolls back already-written text and leaves current history intact',()=>{const data=new Map([['sessions','original'],['prefs','original prefs']]);const storage={getItem:k=>data.get(k)??null,setItem(k,v){if(k==='prefs'&&v!=='original prefs')throw Error('quota');data.set(k,v);},removeItem:k=>data.delete(k)};assert.throws(()=>writeStorageBatch(storage,{sessions:['new'],prefs:{theme:'dark'}}),/restored/);assert.equal(data.get('sessions'),'original');assert.equal(data.get('prefs'),'original prefs');assert.equal(cleanPreferences({token:'secret'}).token,undefined);});
